---
Name: sectionblockconfig
After:
  - 'framework/*'
  - 'cms/*'
---
Injector:
  SSTemplateParser:
    properties:
      closedBlocks:
        template: ['\Moo\Template\Parser\SectionBlock', 'template']
        set: ['\Moo\Template\Parser\SectionBlock', 'setTemplateVar']
#      openBlocks:
#        set: ['\Moo\Template\Parser\SectionBlock', 'arg']
